version: '3'
networks:
  raiden_net_8:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.8.144.0/16

services:
  raiden_0x979a2a0055f34e13f1d89ee61b7b6ce5a9beb04b: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x979a2a0055f34E13f1d89EE61B7B6CE5A9beb04b' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xf1af41691c37da1b83f13562b520c8eadc540113: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xF1AF41691C37da1B83f13562B520C8eADC540113' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x767e927f48b49fdf12870e650dc9b5f84734dbc7: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x767e927f48b49fdf12870E650dC9B5F84734dbc7' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x6bc9f16a08833a9cd8ce86a977e5d3f89fb08ab1: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x6bC9F16A08833a9Cd8ce86A977E5D3F89fB08aB1' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xcc13372a1777a8e4d86fccf9ca781f3a65d8ebb7: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xCC13372a1777A8e4D86FcCf9CA781f3A65D8EBB7' 
      --password-file ./data/password.txt
      --web-ui

