version: '3'
networks:
  raiden_net_4:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.4.144.0/16

services:
  raiden_0x04810e7dcaf1755d2b00791676542871dc8e6f03: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_4: 
        ipv4_address: '172.4.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x04810e7DcaF1755d2b00791676542871dC8E6F03' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xc5fcac5832f4e07675a8eeea1141e42106ec9028: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_4: 
        ipv4_address: '172.4.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xc5fcac5832f4E07675A8EeEa1141E42106eC9028' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xe9ccd934853083ff28e839f0fe8c7b040f01251a: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_4: 
        ipv4_address: '172.4.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xe9cCd934853083ff28E839f0fe8c7B040f01251A' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xb4d6f6b2f9227984c355bc94339d7be7a7bd0026: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_4: 
        ipv4_address: '172.4.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xb4D6f6b2F9227984c355bc94339d7bE7a7bd0026' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x4cae7d23f390b1c115e0ddb6e1cccef7fca50526: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_4: 
        ipv4_address: '172.4.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x4cae7d23f390b1C115E0Ddb6E1CCCeF7fCa50526' 
      --password-file ./data/password.txt
      --web-ui

