version: '3'
networks:
  raiden_net_1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.1.144.0/16

services:
  raiden_0x2d6b83487782f207705562393b576cacb6eeb363: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_1: 
        ipv4_address: '172.1.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x2d6B83487782F207705562393B576cacB6eEb363' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x31c9e85f24be42764e3a42d1c9be260e794f84ca: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_1: 
        ipv4_address: '172.1.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x31c9e85f24bE42764E3a42D1C9Be260e794F84ca' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x625cf771c42f503f3256276a993a0bee24f13171: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_1: 
        ipv4_address: '172.1.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x625CF771c42f503F3256276A993A0Bee24F13171' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x749b7071001b4dfd5f00a64a0446c500850618e3: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_1: 
        ipv4_address: '172.1.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x749b7071001b4DFD5F00a64A0446c500850618e3' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xe8eefa56ba24b560154fc5bf8ffde68d215830a0: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_1: 
        ipv4_address: '172.1.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xe8eEFa56bA24B560154fC5Bf8FFDe68d215830A0' 
      --password-file ./data/password.txt
      --web-ui

