version: '3'

services:

  netting_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.16'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0xD552f5fC6520C202E7263b8243A24e0cFB78749c"
      --password-file ./data/password.txt

  raiden_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.15'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x559B958D60DE2Bc30eB0B22097D1AC34317B535D"
      --password-file ./data/password.txt

  raiden_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.2'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x37012840cf69Ee0297bE9bF8E11413df7c951FC0"
      --password-file ./data/password.txt

  raiden_3:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.3'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x2F3a0db383A23dBD10f18c8D72cCeEedCcDcAdc5"
      --password-file ./data/password.txt

  raiden_4:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.4'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0xD0E657E60E3Df58018A65f95eA44C4c49F387131"
      --password-file ./data/password.txt

  raiden_5:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.5'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0xc59A87424275b462C9be66BD9043cec482cBD54c"
      --password-file ./data/password.txt

  raiden_6:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.6'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x512031Ea75daC4d8AA18683EE4B9092Ec110E8c6"
      --password-file ./data/password.txt

  raiden_7:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.7'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x88AdFE04F27B7d51d3b00F4F18Ec79605ff76936"
      --password-file ./data/password.txt
  
networks:
  raiden_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16
