version: '3'

services:

  raiden_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.15'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x02516D1af993Fb82089473117D714B1A1f5d86dE"
      --password-file ./data/password.txt

  raiden_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.2'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0xC466cd9A677eB2fc800C1f44c5EE78b58Bb21525"
      --password-file ./data/password.txt

  raiden_3:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.3'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0xC2Cc3E9B2aE39f17F17544d27336C9F301ee39C4"
      --password-file ./data/password.txt
  
networks:
  raiden_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16
