version: '3'

networks:
  raiden_net-1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16

services:

  raiden_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.15'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x559B958D60DE2Bc30eB0B22097D1AC34317B535D"
      --password-file ./data/password.txt

  raiden_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.2'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x37012840cf69Ee0297bE9bF8E11413df7c951FC0"
      --password-file ./data/password.txt

  raiden_3:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net:
        ipv4_address: '172.13.0.3'
    command:
      --keystore-path ./data/keystore
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/9081143fcc3e4533ae4cc3e26ff0a586
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --web-ui
      --address "0x2F3a0db383A23dBD10f18c8D72cCeEedCcDcAdc5"
      --password-file ./data/password.txt
  
networks:
  raiden_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16
