version: '3'
networks:
  raiden_net_8:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.8.144.0/16

services:
  raiden_0xfa5ced8dd8d4a0b8e2bf8edf843ca05a2eb74c33: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xFa5CED8dD8d4a0b8e2BF8eDf843Ca05a2eb74C33' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xccc002ce8ddd086262b02af17c22e79eb74b56f6: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xccc002cE8DDD086262B02aF17C22e79Eb74b56F6' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xace8ace833205b140b8a1477f09eaf59d55f9fd2: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xaCE8Ace833205b140b8a1477F09EAf59d55f9fD2' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xe9d1dd02c92a330a4bf5d493dcc3c6be4f0acca6: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xe9D1dD02c92a330a4BF5D493dcC3C6be4F0AccA6' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xfd302a9f2c0fbeba8a85c2f696e4d7423281fb4f: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_8: 
        ipv4_address: '172.8.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xFd302A9F2c0FBEbA8A85c2f696e4D7423281fB4F' 
      --password-file ./data/password.txt
      --web-ui

