version: '3'
networks:
  raiden_net_5:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.5.144.0/16

services:
  raiden_0x83d0612073094f990dff2829e63089c9777dd19b: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_5: 
        ipv4_address: '172.5.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x83d0612073094F990dFF2829e63089c9777dd19b' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xdc46795eafdf63b8ce2d03571659d1d5719aada0: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_5: 
        ipv4_address: '172.5.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xDC46795EafdF63b8ce2D03571659d1D5719AAdA0' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x39d32f7a258eea542f0c20db43ae3c929ea02944: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_5: 
        ipv4_address: '172.5.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x39d32f7a258eEa542f0c20dB43ae3C929Ea02944' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x439fc6e4a9d7e5813ec74d42acdc4d56b1de66e2: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_5: 
        ipv4_address: '172.5.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x439FC6E4A9d7E5813EC74d42ACdC4D56B1de66e2' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x61f6d5765fe319b4d45f4f1d177b89648496536d: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_5: 
        ipv4_address: '172.5.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x61F6D5765FE319b4D45F4f1d177B89648496536d' 
      --password-file ./data/password.txt
      --web-ui

