version: '3'
networks:
  raiden_net_3:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.3.144.0/16

services:
  raiden_0x11e2a6ea72dd0ea968105059f1cf8e645060f170: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_3: 
        ipv4_address: '172.3.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x11e2a6ea72dD0EA968105059F1CF8E645060F170' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xdec4e0df5eab1313a8edb361c745a6eb72e0bd21: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_3: 
        ipv4_address: '172.3.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xdEC4e0Df5Eab1313a8EDB361c745a6eb72e0bD21' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x7815a57b581dddb5ebdf052461d869771015ea91: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_3: 
        ipv4_address: '172.3.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x7815a57B581DDdB5EBDF052461d869771015EA91' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xca5133c9530df845887828f792add8d23b130251: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_3: 
        ipv4_address: '172.3.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xCA5133c9530dF845887828F792aDd8D23B130251' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xdea1b754df87741c68fa19b5bdf2449a3885bdc1: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_3: 
        ipv4_address: '172.3.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xdeA1B754df87741C68fa19B5bdF2449a3885BDC1' 
      --password-file ./data/password.txt
      --web-ui

