version: '3'
networks:
  raiden_net_1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.1.144.0/16

  raiden_net_2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.2.144.0/16

  raiden_net_3:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.3.144.0/16

services:
  raiden_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_1:
        ipv4_address: '172.1.144.5'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0xB9e409CB667f7b9b01bd27990b254E287e9F883F'
      --password-file ./data/password.txt
      --web-ui

  raiden_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_1:
        ipv4_address: '172.1.144.6'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0xcBf7cD645cd3af6E290A3B3dfF7975F1F01A65C6'
      --password-file ./data/password.txt
      --web-ui

  raiden_3:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_1:
        ipv4_address: '172.1.144.7'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0xba083Bf70dc7F87f86E373c2A339Ba0CAbB7DB73'
      --password-file ./data/password.txt
      --web-ui

  raiden_4:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_1:
        ipv4_address: '172.1.144.8'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0xCfAE51B132Ae3790cd5F0010132D89C65Dd009Dd'
      --password-file ./data/password.txt
      --web-ui

  raiden_5:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_1:
        ipv4_address: '172.1.144.9'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0xb0950b70A66F69f83b9640d86e818F7Fa00e3457'
      --password-file ./data/password.txt
      --web-ui

  raiden_6:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_2:
        ipv4_address: '172.2.144.5'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0xDD0fd07f3f6bd465878f45B42227Fb6f3F512eE3'
      --password-file ./data/password.txt
      --web-ui

  raiden_7:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_2:
        ipv4_address: '172.2.144.6'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x37385295BdB94FBBFd153FcF89D9feECA63Ea742'
      --password-file ./data/password.txt
      --web-ui

  raiden_8:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_2:
        ipv4_address: '172.2.144.7'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x2098671A0bc9AFB552Fb276f54BA03F039a30d37'
      --password-file ./data/password.txt
      --web-ui

  raiden_9:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_2:
        ipv4_address: '172.2.144.8'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x691b5C8706e19ad83ed49203eF590224bCE300b1'
      --password-file ./data/password.txt
      --web-ui

  raiden_10:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_2:
        ipv4_address: '172.2.144.9'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x564a53EC4D33245F5B0AEd2AA2Ec3a7f683CfBa7'
      --password-file ./data/password.txt
      --web-ui

  raiden_11:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_3:
        ipv4_address: '172.3.144.5'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0xF625e48C073dC4bB925D4F454Dcf006F739080fe'
      --password-file ./data/password.txt
      --web-ui

  raiden_12:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_3:
        ipv4_address: '172.3.144.6'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x0449a557a8Aaea18376CDc88344B6Ad44184B7Eb'
      --password-file ./data/password.txt
      --web-ui

  raiden_13:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_3:
        ipv4_address: '172.3.144.7'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x90b078b10A114DC09b9c11865A427c011F62A5e7'
      --password-file ./data/password.txt
      --web-ui

  raiden_14:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_3:
        ipv4_address: '172.3.144.8'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x1Fb20E3E301749856C16F5194Cd31BB483321E4a'
      --password-file ./data/password.txt
      --web-ui

  raiden_15:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './data:/data'
    networks:
      raiden_net_3:
        ipv4_address: '172.3.144.9'
    command:
      --keystore-path ./data/keystore/used
      --network-id goerli
      --eth-rpc-endpoint https://goerli.infura.io/v3/20a2ed4fef6248c2922a3d63fb004698
      --gas-price fast
      --environment-type development
      --api-address 0.0.0.0:5001
      --accept-disclaimer
      --address '0x9A0fCeAa2318c1a5A6646E28610081FF9AeB4e01'
      --password-file ./data/password.txt
      --web-ui
