version: '3'
networks:
  raiden_net_6:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.6.144.0/16

services:
  raiden_0xaf5e3473fad44fd0415eeb3aae11ae3723dcb12e: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_6: 
        ipv4_address: '172.6.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xAf5e3473Fad44fd0415Eeb3aaE11Ae3723dCB12e' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xc28aa5a8ff14f01bcb4dbb01bbe2cb28bdb3872a: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_6: 
        ipv4_address: '172.6.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xc28aA5A8fF14f01BcB4DbB01BBe2cb28BDb3872A' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x11ec68f4f5d3d11e1d689a10e86df99a040ef622: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_6: 
        ipv4_address: '172.6.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x11eC68f4f5D3d11E1d689a10e86df99a040ef622' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x14cda916c0e4fc5848d1f85b90d6d4999fde107b: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_6: 
        ipv4_address: '172.6.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x14cDA916C0E4fC5848d1F85b90D6D4999fde107B' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x596eea6412e1a67a55648f0c296ef376d2e605d8: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_6: 
        ipv4_address: '172.6.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x596EEa6412E1a67a55648F0c296eF376D2e605D8' 
      --password-file ./data/password.txt
      --web-ui

