version: '3'
networks:
  raiden_net_7:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.7.144.0/16

services:
  raiden_0xb0d55115f09cf3505698abefa321b1c409ba8177: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_7: 
        ipv4_address: '172.7.144.5' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xb0D55115f09Cf3505698abEFA321B1C409bA8177' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x6534b77931b2ac20a99990ef965116936b70b386: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_7: 
        ipv4_address: '172.7.144.6' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x6534B77931B2AC20a99990Ef965116936b70b386' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x54c9ca01ac2c2d9f1294ba74ccbc59d5ed46c5d8: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_7: 
        ipv4_address: '172.7.144.7' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x54c9ca01ac2c2D9F1294BA74CCBc59d5eD46C5d8' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0x71731c89b7c919ec2baf1506972eee830ee641f6: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_7: 
        ipv4_address: '172.7.144.8' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0x71731c89b7c919eC2baF1506972EEe830EE641f6' 
      --password-file ./data/password.txt
      --web-ui

  raiden_0xcfb0fcdddd5183dbb7d8b440b03d0175a412c5f9: 
    build:
      context: . 
      dockerfile: ./Dockerfile 
    volumes: 
      - './data:/data' 
    networks: 
      raiden_net_7: 
        ipv4_address: '172.7.144.9' 
    command: 
      --keystore-path ./data/keystore 
      --network-id goerli 
      --eth-rpc-endpoint https://goerli.infura.io/v3/568d1aa1488f4d3ca4be7ba148703e01 
      --gas-price fast 
      --environment-type development 
      --api-address 0.0.0.0:5001 
      --accept-disclaimer 
      --address '0xcfb0FCDDdD5183DbB7d8b440b03D0175a412c5f9' 
      --password-file ./data/password.txt
      --web-ui

